load secrets from volume

diff --git a/rosa/rosa-cluster-create-task.yaml b/rosa/rosa-cluster-create-task.yaml
--- a/rosa/rosa-cluster-create-task.yaml
+++ b/rosa/rosa-cluster-create-task.yaml
@@ -6,24 +6,35 @@ metadata:
 spec:
   results:
     - name: ocp-login-command
-      description: The command to login to the created cluster 
+      description: The command to login to the created cluster
   params:
     - name: version
+      type: string
       description: ocp cluster version that you want to create
     - name: region
+      type: string
       description: ocp cluster region where you want to create
-      default: "us-east-1"
     - name: name
+      type: string
       description: ocp cluster name that you want to create
     - name:  machine-type
+      type: string
       description: ocp cluster machine type that you want to create
       default: "m5.2xlarge"
     - name: node_number
+      type: string
       description: number of worker nodes to provision
       default: "3"
+  volumes:
+    - name: secret-volume
+      secret:
+        secretName: hcp-cluster-secret
   steps:
     - name: create-cluster
       image: quay.io/redhat-pipeline-service/ci-runner:main
+      volumes:
+        - name: secret-volume
+          mountPath: /workspace
       env:
         - name: CLUSTER_NAME
           value: "$(params.name)"
@@ -33,63 +44,20 @@ spec:
           value: "$(params.version)"
         - name: MACHINE_TYPE
           value: "$(params.machine-type)"
-        - name: ROSA_TOKEN
-          valueFrom:
-            secretKeyRef:
-              name: hcp-cluster-secret
-              key: "rosa_token"
-        - name: AWS_ACCESS_KEY_ID
-          valueFrom:
-            secretKeyRef:
-              name: hcp-cluster-secret
-              key: "aws_access_key_id"
-        - name: AWS_SECRET_ACCESS_KEY
-          valueFrom:
-            secretKeyRef:
-              name: hcp-cluster-secret
-              key: "aws_secret_access_key"
-        - name: BILLING_ACCOUNT_ID
-          valueFrom:
-            secretKeyRef:
-              name: hcp-cluster-secret
-              key: "AWS_ACCOUNT_ID"
-        - name: AWS_OIDC_CONFIG_ID
-          valueFrom:
-            secretKeyRef:
-              name: hcp-cluster-secret
-              key: "AWS_OIDC_CONFIG_ID"
-        - name: OPERATOR_ROLES_PREFIX
-          valueFrom:
-            secretKeyRef:
-              name: hcp-cluster-secret
-              key: "OPERATOR_ROLES_PREFIX"
-        - name: SUBNET_IDS
-          valueFrom:
-            secretKeyRef:
-              name: hcp-cluster-secret
-              key: "SUBNET_IDS"
-        - name: INSTALL_ROLE_ARN
-          valueFrom:
-            secretKeyRef:
-              name: hcp-cluster-secret
-              key: "INSTALL_ROLE_ARN"
-        - name: SUPPORT_ROLE_ARN
-          valueFrom:
-            secretKeyRef:
-              name: hcp-cluster-secret
-              key: "SUPPORT_ROLE_ARN"
-        - name: WORKER_ROLE_ARN
-          valueFrom:
-            secretKeyRef:
-              name: hcp-cluster-secret
-              key: "WORKER_ROLE_ARN"
       script: |
         set -o errexit
         set -o nounset
         set -o pipefail
 
+        config_aws_creds() {
+            printf "INFO: Configure AWS Credentials...\n" 
+            aws configure set aws_access_key_id $(cat /workspace/aws_access_key_id)
+            aws configure set aws_secret_access_key $(cat /workspace/aws_secret_access_key)
+            aws configure set region $(params.AWS_REGION)
+        }
+
         print_debug_info() {
-            printf "Print debug info......\n" 
+            printf "INFO: Print debug info......\n" 
             rosa --region "$REGION" describe cluster --cluster="$CLUSTER_NAME"
         }
 
@@ -112,7 +80,7 @@ spec:
                 done
                 # if the operator is still not available after 10 times, exit 1
                 if [ "$retries" -eq "$max_retries" ]; then
-                    echo "Operator $operator is not available" >&2
+                    echo "ERROR: Operator $operator is not available" >&2
                     # print the status of all cluster operators
                     kubectl get co
                     # print the status of the failed cluster operator
@@ -120,7 +88,7 @@ spec:
                     exit 1
                 fi
             done
-            echo "Operators [${operators}] are available"
+            echo "INFO: Operators [${operators}] are available"
             # for debugging purpose
             kubectl get co
         }
@@ -136,28 +104,28 @@ spec:
         }
 
         deploy_cluster() {
-            printf "Log in to your Red Hat account...\n" 
-            setx_off
+            printf "INFO: Log in to your Red Hat account...\n" 
+            config_aws_creds
             rosa login --token="$ROSA_TOKEN"
-            setx_on
 
             printf "Create ROSA with HCP cluster...\n" 
             get_hcp_full_version
             rosa create cluster --cluster-name "$CLUSTER_NAME" \
-                --sts --mode=auto --oidc-config-id "$AWS_OIDC_CONFIG_ID" \
-                --operator-roles-prefix "$OPERATOR_ROLES_PREFIX" --region "$REGION" --version "$HCP_FULL_VERSION" \
-                --role-arn "$INSTALL_ROLE_ARN" \
-                --support-role-arn "$SUPPORT_ROLE_ARN" \
-                --worker-iam-role "$WORKER_ROLE_ARN" \
+                --sts --mode=auto --oidc-config-id $(cat /workspace/AWS_OIDC_CONFIG_ID) \
+                --operator-roles-prefix $(cat /workspace/OPERATOR_ROLES_PREFIX) --region "$REGION" --version "$HCP_FULL_VERSION" \
+                --role-arn $(cat /workspace/INSTALL_ROLE_ARN) \
+                --support-role-arn $(cat /workspace/SUPPORT_ROLE_ARN) \
+                --worker-iam-role "$(cat /workspace/WORKER_ROLE_ARN)" \
                 --compute-machine-type "$MACHINE_TYPE" \
-                --subnet-ids="$SUBNET_IDS" \
-                --billing-account "$AWS_ACCOUNT_ID" \
+                --subnet-ids "$(cat /workspace/WORKER_ROLE_ARN)" \
+                --billing-account $(cat /workspace/AWS_ACCOUNT_ID) \
+                --replicas $(params.node_number)
                 --hosted-cp -y
 
-            printf "Track the progress of the cluster creation...\n" 
+            printf "INFO: Track the progress of the cluster creation...\n" 
             rosa logs install --cluster="$CLUSTER_NAME" --region "$REGION" --watch
 
-            printf "ROSA with HCP cluster is ready, create a cluster admin account for accessing the cluster\n" 
+            printf "INFO: ROSA with HCP cluster is ready, create a cluster admin account for accessing the cluster\n" 
             admin_output="$(rosa create admin --region "$REGION" --cluster="$CLUSTER_NAME")"
 
             # Get the admin account credentials and API server URL
@@ -165,13 +133,16 @@ spec:
             admin_pass="$(echo "$admin_output" | grep -oP '(?<=--password ).*')"
             api_url="$(echo "$admin_output" | grep -oP '(?<=oc login ).*(?= --username)')"
 
+            printf "INFO: Storing login command...\n"
+            echo "oc login $api_url --username $admin_user --password $admin_pass" > $(results.ocp-login-command.path)
+
             # Use the admin account to login to the cluster in a loop until the account is active.
             max_retries=10
             retries=0
             export KUBECONFIG="$KUBECONFIG_DIR/config"
             while ! oc login "$api_url" --username "$admin_user" --password "$admin_pass" >/dev/null 2>&1; do
                 if [ "$retries" -eq "$max_retries" ]; then
-                    echo "[ERROR] Failed to login the cluster." >&2
+                    echo "ERROR: Failed to login the cluster." >&2
                     print_debug_info
                     exit 1
                 fi
@@ -180,12 +151,9 @@ spec:
                 echo "Retried $retries times..."
             done
 
-            printf "The following is the cluster kubeconfig:\n" 
-            cat "$KUBECONFIG"
-
             #Workaround: Check if apiserver is ready by calling kubectl get nodes
             if ! timeout 300s bash -c "while ! kubectl get nodes >/dev/null 2>/dev/null; do printf '.'; sleep 10; done"; then
-                echo "API server is not ready" >&2
+                echo "ERROR: API server is not ready" >&2
                 exit 1
             fi
             check_clusteroperators
